# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.HEHE }}

          # Options
          user: H4ckerxx44
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: detailed # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 1000
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_from: 1000       # Use 1000 events to compute habits
          plugin_habits_days: 30         # Keep only events from last 30 days
          plugin_habits_facts: yes       # Display facts section
          plugin_habits_charts: yes      # Display charts section
          plugin_habits_trim: no         #  Do not trim unused hours on daily chart
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_skipped: my-test-repo                        # List of repositories to skip
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: "0:orange"  # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "Python:Py" # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 30                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: dennis.wortmann1999@gmail.com              # Surnames or email addresses used to identify your commits
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4
          plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: yes
