- name: Metrics embed
  uses: lowlighter/metrics@v3.16

  with:
    # ... other options
    plugin_habits: yes
    plugin_habits_from: 1000       # Use 1000 events to compute habits
    plugin_habits_days: 30         # Keep only events from last 30 days
    plugin_habits_facts: yes       # Display facts section
    plugin_habits_charts: yes      # Display charts section
    plugin_habits_trim: no         #  Do not trim unused hours on daily chart
    config_timezone: Europe/Berlin  # Set timezone
