- name: Metrics embed
  uses: lowlighter/metrics@v3.16

  with:
    # ... other options
    plugin_isocalendar: yes
    plugin_isocalendar_duration: full-year # Display full year instead of half year
